import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Pusher from "pusher-js";
import { useEffect } from "react";
import { useQueryClient } from "react-query";
Pusher.logToConsole = true;

var pusher = new Pusher("f48d597a5baeec8518de", {
  cluster: "sa1",
});

var channel = pusher.subscribe("orders");

const Home: NextPage = () => {
  const orders = trpc.useQuery(["orders.getAll"]);

  const queryClient = useQueryClient();
  useEffect(() => {
    const ch = channel.bind("new-order", function (data: any) {
      // alert(JSON.stringify(data));
      queryClient.cancelQueries("orders.getAll");

      queryClient.setQueryData("orders.getAll", (old: any) => [data, ...old]);
      orders.refetch();
    });
    return () => {
      ch.unbind_all();
      ch.cancelSubscription();
    };
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="p-8 flex flex-col gap-4">
        <h1 className="text-2xl">Ordenes</h1>
        {orders.data?.map((order) => (
          <div key={order.id} className="p-2 rounded-md bg-brand-grey">
            <div className="p-2 round-full  text-brand-blue">{order.name}</div>
            <div className="p-2 round-full  text-brand-blue">
              {order.description}
            </div>
          </div>
        ))}
      </div>
    </>
  );
};

export default Home;
